### ISSUE TITLE
Selectors do not hot reload

### ISSUE THREAD

**Issue by slorber** [reactjs/reselect#83] opened 2016-02-17 11:46 UTC
With webpack hot reloading, when fixing a bug inside a selector, the React view does not reflect the change after hot reloading.

Any reason for this? 

Maybe the memoized values should be trashed on reload?
Or maybe it's react-redux connect that should reconnect on selectors updates?

**Comment by gaearon** [comment] 2016-02-17 12:16
My guess is they will hot reload it you use React Hot Loader but not React Transform because https://github.com/gaearon/babel-plugin-react-transform/issues/26. This is not specific to selectors at all: the bigger issue is we don’t update the wrapper components currently.

**Comment by slorber** [comment] 2016-02-17 12:33
@gaearon thanks for the link will check it.

But I'm currently using React Hot Loader and not a babel transform :)

**Comment by gaearon** [comment] 2016-02-17 12:48
Can you set up a small project reproducing the issue?

**Comment by slorber** [comment] 2016-02-17 14:50
Hmmm thinking about it, this probably happens because I don't use Reselect with Redux so I guess it may work better if replaceReducer of redux is triggered and the selectors are in the same file as the reducers?

I'll have to investigate a bit more but I don't have time right now

**Comment by gaearon** [comment] 2016-02-17 22:10
It has more to do with where updates bubble then what selector is like. If you import selectors from components, React Hot Loader should pick up the updates. If it doesn’t, please post a project reproing this so I can look.

**Comment by ellbee** [comment] 2016-02-24 20:06
@slober I'm going to close this for now, if you find the time to create a reproducible test case please feel free to re-open.

**Closed by ellbee** 2016-02-24 20:06 UTC

**Comment by gaearon** [comment] 2016-02-29 04:57
You might be interested in https://github.com/reactjs/redux/pull/1455.

**Comment by slorber** [comment] 2016-02-29 18:02
thanks will check that

**Comment by gaearon** [comment] 2016-04-18 14:31
This is fixed in [React Hot Loader 3](https://github.com/gaearon/react-hot-boilerplate/pull/61).
It is built with lessons learned from both React Hot Loader and React Transform.
It’s still in alpha but I encourage you to [check it out](https://github.com/gaearon/react-hot-boilerplate/pull/61)!
